Repository DOTOREAD/DOTOREAD-CLIENT, pull requests merged in 2024-12, with the labels that each got.

#82 [ Feat ] 공유 페이지 전체 글 목록 조회 api 연결
  src/pages/Share/Collection.tsx
  src/pages/Share/SharePage.tsx
Labels: ✨ Feature

#83 [ Feat ] 공유 페이지 글 좋아요 , 좋아요 취소 api 연결
  src/pages/Share/ModalContent.tsx
Labels: ✨ Feature

#85 [ Feat ] 컬렉션 검색 api 연결
  src/pages/Share/SearchBar.tsx
  src/pages/Share/SharePage.tsx
Labels: ✨ Feature

#90 [ Feat ] 공유 페이지 단일 글 상세 조회 api 연결
  src/pages/Share/Collection.tsx
  src/pages/Share/ModalContent.tsx
  src/pages/Share/SharePage.tsx
Labels: ✨ Feature

#92 [ style ] 북마크 추가하기 페이지 퍼블리싱 및 모든 북마크 api 연결
  src/assets/Vector.svg
  src/components/common/Modal/CollectionModal.tsx
  src/components/common/Modal/NewArticleModal.tsx
  src/constants/ButtonList.ts
  src/pages/Share/AddBookMark.tsx
  src/pages/Share/ArticleContent.tsx
  src/pages/Share/ArticleItem.tsx
  src/pages/Share/BookMarkItem.tsx
  src/pages/Share/SharePage.tsx
Labels: ✨ Feature

#94 [ Fix ] conflict 에러 해결
  src/pages/Share/SharePage.tsx
Labels: 🐞 BugFix

#97 [ Feat ] 새 글 북마크 추가 api 연결
  src/pages/Share/AddBookMark.tsx
  src/pages/Share/BookMarkItem.tsx
  src/pages/Share/SharePage.tsx
Labels: ✨ Feature

#99 [ Feat ] 글 작성용 북마크 조회 api 연결
  src/pages/Share/AddBookMark.tsx
  src/pages/Share/ArticleContent.tsx
  src/pages/Share/SharePage.tsx
Labels: ✨ Feature

#101 [ Fix ] 빌드 에러 해결
  src/assets/Donates.svg
  src/pages/Mission/MissionPage.tsx
Labels: 🐞 BugFix

#103 [ Fix ] 빌드 에러 해결
  src/assets/Karas.svg
  src/constants/DonateContents.ts
Labels: 🐞 BugFix

#106 Feat/#105/missionpage qa
  src/pages/Share/ArticleContent.tsx
  src/pages/Share/Collection.tsx
Labels: ✨ Feature

#108 [ Feat ] 드롭다운 관련 QA 반영
  src/components/BookMarkSlide/BookMarkSlide.tsx
  src/components/common/Button/BookMarkListBtn.tsx
  src/components/common/Button/SortBtn.tsx
Labels: ✨ Feature, 🎨 Style

#112 [ Feat ] 메인 페이지 대시보드 api 연결
  src/components/common/SideBar/SideBar.tsx
  src/components/common/SideBar/Storage.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Main/components/CircleGraph.tsx
  src/pages/Main/components/PrgressCircle.tsx
Labels: ✨ Feature

#114 [ Feat ] 2차 QA 반영
  src/assets/BookMark.svg
  src/assets/BookMarkClicked.svg
  src/assets/Logo.svg
  src/components/common/Header/SearchBar.tsx
  src/pages/BookMark/ListItem.tsx
  src/pages/Share/ArticleContent.tsx
  src/pages/Share/ListItem.tsx
Labels: ✨ Feature

#116 [ Feat ] 도토리 알림 모달 api(사용 내역, 적립 내역) 연결
  src/assets/MiniAcorn.svg
  src/components/common/Header/Header.tsx
Labels: ✨ Feature

#119 [ Feat ] 2차 QA 반영
  src/assets/AiChange.svg
  src/assets/ArrowDown.svg
  src/assets/Onboard1backgroudn.svg
  src/assets/Onboard3-1.svg
  src/assets/Onboard3-2.svg
  src/assets/Onboard3-3.svg
  src/assets/Onboard3-4.svg
  src/assets/Onboard3.svg
  src/assets/Onboarding4-1.svg
  src/assets/Onboarding4-11.svg
  src/assets/Onboarding4-2.svg
  src/components/AiClassification/AiClassificationPage.tsx
  src/components/common/Header/Header.tsx
  src/pages/OnBoarding/components/OnBoardingPage/OnBoarding1.tsx
  src/pages/OnBoarding/components/OnBoardingPage/OnBoarding2.tsx
  src/pages/OnBoarding/components/OnBoardingPage/OnBoarding3.tsx
  src/pages/OnBoarding/components/OnBoardingPage/OnBoarding4.tsx
  src/styles/theme.ts
Labels: 🎨 Style

#120 [ Feat ] 드래그앤드롭 구현 및 api 연결
  package.json
  src/App.tsx
  src/components/BookMarkSlide/BookMarkSlide.tsx
  src/components/common/Button/BookMarkListBtn.tsx
  src/components/common/Header/Header.tsx
  src/components/common/SideBar/SideBar.tsx
  src/contexts/CurrentCategoryContext.tsx
  src/pages/BookMark/BookMarkPage.tsx
  src/pages/BookMark/ListItem.tsx
  yarn.lock
Labels: ✨ Feature

#124 [ Feat ] 공유페이지 새 글 작성 api 연결
  src/components/common/Header/Header.tsx
  src/pages/BookMark/BookMarkPage.tsx
  src/pages/Share/ArticleContent.tsx
  src/pages/Share/SharePage.tsx
Labels: ✨ Feature

#127 [ Feat ] 북마크 클릭시 api 연결
  src/components/AiClassification/AiClassificationPage.tsx
  src/components/AiClassification/ClassificationArticle.tsx
  src/components/BookMarkSlide/BookMarkSlide.tsx
  src/components/common/Button/ExecutionBtn.tsx
  src/components/common/Header/Header.tsx
  src/components/common/SideBar/Storage.tsx
  src/pages/BookMark/BookMarkPage.tsx
  src/pages/BookMark/ListItem.tsx
Labels: ✨ Feature

#128 [ Feat ] 후원하기 모달 퍼블리싱 및 API
  src/assets/IconBackground.svg
  src/assets/MinusIc.svg
  src/assets/PlusIc.svg
  src/components/Mission/DonateArticle.tsx
  src/components/common/Modal/DonateModal.tsx
  src/pages/Mission/MissionPage.tsx
Labels: ✨ Feature, 🎨 Style

#131 [ Fix] 후원하기 모달 닫을 때 사용할 도토리 0으로 초기화
  src/pages/Mission/MissionPage.tsx
Labels: 🐞 BugFix

#133 [ Fix ] 새 글 작성시 내용 안뜨는 버그 해결
  src/pages/Share/ArticleContent.tsx
  src/pages/Share/SharePage.tsx
Labels: 🐞 BugFix
