Repository DOTOREAD/DOTOREAD-CLIENT, pull requests merged in 2024-11, with the labels that each got.

#23 [ Style ] AI 분류하기 공통 컴포넌트 구현
  src/Router.tsx
  src/assets/Ai.svg
  src/assets/Ai_Delete.svg
  src/assets/Article_Folder.svg
  src/components/AiClassification/AiClassificationPage.tsx
  src/components/AiClassification/ClassificationArticle.tsx
  src/components/common/Button/AiClassificationBtn.tsx
  src/components/common/Button/Btn.tsx
  src/constants/AiClassificationList.ts
  src/constants/ButtonList.ts
  src/constants/ListItems.ts
  src/styles/theme.ts
Labels: 🎨 Style

#26 [ Style ] 북마크 리스트 공통 컴포넌트 나머지 구현
  src/assets/LucideGray.svg
  src/assets/LucideOrange.svg
  src/assets/react.svg
  src/components/BookMarkSlide/BookMarkSlide.tsx
  src/components/common/BookMarkList/ListItem.tsx
  src/components/common/Button/Btn.tsx
  src/components/common/SideBar/SideBar.tsx
  src/constants/ListItems.ts
  src/pages/BookMark/BookMarkList.tsx
  src/pages/BookMark/BookMarkPage.tsx
  src/pages/BookMark/Default.tsx
  src/pages/BookMark/ListItem.tsx
  src/pages/BookMark/Navbar.tsx
Labels: ✨ Feature, 🎨 Style

#31 [ Feat ] 구글 로그인 - 수정
  .env
  .gitignore
  package.json
  src/Login.tsx
  src/MainPage.tsx
  src/OnBoardingPage.tsx
  src/Router.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: ✨ Feature

#30 [ Style ] 메인페이지 캐러셀 구현 - 수정
  package.json
  src/assets/arrow-left.svg
  src/assets/arrow-right.svg
  src/components/AiClassification/AiClassificationPage.tsx
  src/components/AiClassification/ClassificationArticle.tsx
  src/components/common/SideBar/SideBar.tsx
  src/components/common/SideBar/Storage.tsx
  src/constants/AiClassificationList.ts
  src/constants/FreshRottenList.ts
  src/constants/ListItems.ts
  src/pages/Main/MainPage.tsx
  src/pages/Main/components/Carousel.tsx
  src/pages/Main/components/CarouselWrapper.tsx
  yarn.lock
Labels: ✨ Feature

#34 [feat] Ai 분류하기 페이지 연결
  src/pages/BookMark/BookMarkList.tsx
  src/pages/BookMark/BookMarkPage.tsx
  src/pages/BookMark/ListItem.tsx
Labels: ♻️ Refactor

#38 [ Fix ] 각종 에러, warning 해결
  package.json
  src/components/AiClassification/AiClassificationPage.tsx
  src/components/AiClassification/ClassificationArticle.tsx
  src/components/BookMarkSlide/BookMarkSlide.tsx
  src/components/common/Button/Btn.tsx
  src/components/common/Header/SearchBar.tsx
  src/components/common/SideBar/SideBar.tsx
  src/pages/Main/components/PrgressCircle.tsx
  src/pages/OnBoarding/components/OnBoardingPage/Header.tsx
  src/pages/OnBoarding/components/OnBoardingPage/OnBoarding2.tsx
  src/pages/OnBoarding/components/OnBoardingPage/OnBoarding3.tsx
  src/pages/OnBoarding/components/OnBoardingPage/OnBoarding4.tsx
Labels: 🐞 BugFix

#42 [ Feat ] 폴더 생성 api 연결
  package.json
  src/components/BookMarkSlide/BookMarkSlide.tsx
  src/components/common/Modal/Modal.tsx
  src/pages/Main/MainPage.tsx
  src/pages/OnBoarding/components/OnBoardingStartPage/Button.tsx
  yarn.lock
Labels: ✨ Feature

#44 [ Feat ] 폴더 조회 api 연결
  src/components/BookMarkSlide/BookMarkSlide.tsx
  src/pages/Main/MainPage.tsx
Labels: ✨ Feature

#46 [ Feat ] 폴더 삭제 api 연결
  src/components/AiClassification/AiClassificationPage.tsx
  src/components/BookMarkSlide/BookMarkSlide.tsx
  src/components/common/Button/BookMarkListBtn.tsx
Labels: ✨ Feature

#52 [ Fix ] 무한루프 해결
  src/App.tsx
  src/components/common/Header/Header.tsx
  src/constants/ListItems.ts
  src/pages/BookMark/BookMarkPage.tsx
  src/pages/BookMark/ListItem.tsx
Labels: 🐞 BugFix

#54 [ Feat ] 북마크 리스트, 캐러셀 아이템 클릭시 해당 링크 새창에 생성
  src/components/AiClassification/ClassificationArticle.tsx
  src/pages/BookMark/ListItem.tsx
  src/pages/Main/components/Carousel.tsx
Labels: ✨ Feature

#57 [ Fix ] 클릭 이벤트 전파 막기
  src/pages/BookMark/BookMarkList.tsx
  src/pages/BookMark/BookMarkPage.tsx
  src/pages/BookMark/ListItem.tsx
Labels: 🐞 BugFix

#59 [ Feat ] 북마크 AI 분류 api
  src/App.tsx
  src/assets/AiDefault.png
  src/components/AiClassification/AiClassificationPage.tsx
  src/components/AiClassification/ClassificationArticle.tsx
  src/contexts/AiClassificationContext.tsx
  src/contexts/BookmarkProvider.tsx
  src/pages/BookMark/BookMarkList.tsx
  src/pages/BookMark/BookMarkPage.tsx
  src/pages/BookMark/ListItem.tsx
  src/pages/Main/components/Carousel.tsx
Labels: ✨ Feature

#63 [Fix] api 호출시 ui에 즉시 반영되도록 수정
  src/App.tsx
  src/components/AiClassification/AiClassificationPage.tsx
  src/components/BookMarkSlide/BookMarkSlide.tsx
  src/components/common/Header/Header.tsx
  src/contexts/FetchFoldersContext.tsx
  src/pages/BookMark/BookMarkList.tsx
  src/pages/BookMark/BookMarkPage.tsx
  src/pages/BookMark/ListItem.tsx
Labels: 🐞 BugFix

#67 [ Fix ] AI 분류 후 navigate 수정
  src/components/AiClassification/AiClassificationPage.tsx
Labels: 🐞 BugFix

#69 각종 버그 fix
  src/components/AiClassification/AiClassificationPage.tsx
  src/components/BookMarkSlide/BookMarkSlide.tsx
  src/contexts/BookmarkProvider.tsx
Labels: 🐞 BugFix

#72 [ Style ] 공유 페이지 구현
  src/assets/FillHeart.svg
  src/assets/MoveToMyBookMark.svg
  src/assets/NicknameProfile.svg
  src/assets/NonfillHeart.svg
  src/assets/PlusIcon.svg
  src/assets/TomyBookmark.svg
  src/components/common/Button/Btn.tsx
  src/components/common/Modal/CollectionModal.tsx
  src/components/common/Modal/NewArticleModal.tsx
  src/components/common/SideBar/SideBar.tsx
  src/constants/AddBookMarkList.ts
  src/constants/ButtonList.ts
  src/constants/CollectionList.ts
  src/pages/Share/ArticleContent.tsx
  src/pages/Share/CollectionContent.tsx
  src/pages/Share/ListItem.tsx
  src/pages/Share/ModalContent.tsx
  src/pages/Share/SearchBar.tsx
  src/pages/Share/SharePage.tsx
  src/styles/theme.ts
Labels: 🎨 Style

#77 [ Fix ] build 에러 해결
  src/components/common/Header/Header.tsx
  src/contexts/BookmarkContext.ts
  src/contexts/BookmarkProvider.tsx
  src/pages/Share/ArticleContent.tsx
  src/pages/Share/CollectionContent.tsx
  src/pages/Share/ModalContent.tsx
  src/pages/Share/SharePage.tsx
Labels: 🐞 BugFix

#78 [ Style ] 새 글 작성 수정
  src/constants/AddBookMarkList.ts
  src/pages/Share/ArticleContent.tsx
  src/pages/Share/ArticleItem.tsx
  src/pages/Share/Collection.tsx
  src/pages/Share/ModalContent.tsx
  src/pages/Share/SharePage.tsx
Labels: 🎨 Style
